- name: get public SSH key
  delegate_to: localhost
  uri:
    url: "{{do_api_url}}/account/keys"
    method: GET
    headers:
      Authorization: "Bearer {{do_oauth_token}}"
  register: ssh_keys

- name: create a new droplet
  delegate_to: localhost
  digital_ocean_droplet:
    state: present
    name: "{{inventory_hostname}}"
    oauth_token: "{{do_oauth_token}}"
    size: "{{do_droplet_size}}"
    region: "{{do_region}}"
    image: "{{do_image}}"
    ssh_keys: "{{ssh_keys.json | json_query('ssh_keys[*].id')}}"
    wait_timeout: 500
    unique_name: yes
  register: droplet

- name: Create A record via CloudFlare
  delegate_to: localhost
  cloudflare_dns:
    zone: "{{inventory_hostname.split('.')[1:] | join('.') }}"
    record: "{{inventory_hostname.split('.') | first}}"
    type: A
    value: "{{droplet.data.ip_address}}"
    account_email: "{{cf_username}}"
    account_api_token: "{{cf_api_token}}"
  register: record

- name: wait a bit for DNS records to update
  remote_user: root
  when: droplet.changed
  wait_for_connection:
