---
- name: prepare virtualization platform
  hosts: localhost
  tasks:
    - name: install virtualization packages
      become: yes
      yum:
        name:
          - libvirt
          - virt-manager
          - qemu-kvm
          - virt-viewer
    - name: enable libvirt at boot
      become: yes
      systemd:
        service: libvirtd
        enabled: yes
        state: started
